# Generated by Django 2.1.3 on 2018-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0002_auto_20181119_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_color',
            field=models.CharField(default='00cc99', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_color',
            field=models.CharField(default='00cc99', max_length=10),
        ),
    ]
