# Generated by Django 2.1.3 on 2018-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0003_auto_20181119_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('HealthCare', 'HealthCare'), ('Education', 'Education'), ('RetailStores', 'RetailStores'), ('Others', 'Others')], max_length=100),
        ),
    ]
