# Generated by Django 2.1.3 on 2018-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0004_auto_20181119_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(default='https://t4.ftcdn.net/jpg/02/15/84/43/240_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Shopper', 'Shopper'), ('Buyer', 'Buyer'), ('Company_Admin', 'Company_Admin')], max_length=100),
        ),
    ]
