# Generated by Django 2.1.3 on 2018-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('created_by', models.CharField(max_length=200)),
                ('subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('requoted_at', models.DateTimeField(editable=False)),
                ('created_by', models.CharField(max_length=200)),
                ('authorized_buyer', models.CharField(max_length=200)),
                ('expires', models.DateTimeField(editable=False)),
                ('subtotal', models.FloatField()),
            ],
        ),
    ]
