# Generated by Django 2.1.3 on 2018-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='laptop_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='laptop_id',
            field=models.IntegerField(null=True),
        ),
    ]
