# Generated by Django 2.1.3 on 2018-11-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersAPI', '0002_auto_20181119_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
    ]
