# Generated by Django 2.1.3 on 2018-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Workstations', 'Workstations'), ('Servers', 'Servers'), ('Processors', 'Processors'), ('GPU', 'GPU'), ('Accessories', 'Accessories')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('inches', models.FloatField()),
                ('screen_resolution', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('price_euros', models.FloatField()),
                ('photo_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
